### ISSUE TITLE
Add party loot tracker feature

### ISSUE THREAD

**Issue by isilher** [isilher/chronagus#17]
### Description

Add feature to track the common loot of the party

### Tasks

- [ ] Add money tracker with simple addition and subtraction elements.
- [ ] Add list of loot items that can be sorted, added, removed.
- [ ] Add value field to loot items.
- [ ] Add sell for half / sell for full value button to loot items with set value.
